apiVersion: v1
kind: ConfigMap
metadata:
  name: arteci-config
data:
  MINIO_ENDPOINT: "minio-service:9000"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
  MINIO_SECURE: "false"
  MINIO_PROCESSED_BUCKET: "processeddata"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://signoz-otel-collector:4317"